server:
  port: 9090
  servlet:
    context-path: /identity

spring:
  application:
    name: identity-service
  datasource:
    url: "jdbc:mysql://localhost:3308/identity_service"
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  main:
      banner-mode: off

#logging:
#  level:
#    root:

jwt:
  signerKey: "8bliiFZR0IHbKAzA1IRjXVJ0L8MoWIT+wjSLflp9jlphmTfXUTSz5Sn8zk30//Tb"
  valid-duration: 3600 # in seconds
  refreshable-duration: 7200 # in seconds
